# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "kali-workstation" do |kali|
    kali.vm.box = "kali-workstation"
    kali.vm.hostname = "kali-workstation"
    kali.vm.network "public_network"
    kali.vm.communicator = "ssh"
    # kali.ssh.private_key_path = "../../vagrant.id_rsa"
    kali.ssh.username = "vagrant"
    kali.ssh.password = "vagrant"

    kali.vm.provider "hyperv" do |vm|
      vm.linked_clone = true
      vm.enable_enhanced_session_mode = true
      vm.vm_integration_services = {
        # guest_service_interface: true,
        heartbeat: true,
        key_value_pair_exchange: true,
        shutdown: true,
        time_synchronization: true,
        vss: true,
      }
      vm.cpus = "4"
      vm.memory = "4096"
    end
  end
  
  config.vm.define "win10-workstation" do |win10|
    win10.vm.box = "win10-workstation"
    win10.vm.hostname = "win10-workstation"
    win10.vm.network "public_network"
    win10.vm.communicator = "winrm"
    win10.winrm.password = "vagrant"
    win10.winrm.username = "vagrant"

    win10.vm.provider "hyperv" do |vm|
      vm.linked_clone = true
      vm.enable_enhanced_session_mode = true
      vm.vm_integration_services = {
        # guest_service_interface: true,
        heartbeat: true,
        key_value_pair_exchange: true,
        shutdown: true,
        time_synchronization: true,
        vss: true,
      }
      vm.cpus = "4"
      vm.memory = "4096"
    end
  end
end