- name: Provision Image
  hosts: default

  tasks:
    - name: Install Packages
      become: true
      package:
        name:
          - alacritty
          - bspwm
          - dmenu
          - exa
          - feh
          - firefox
          - fish
          - fzf
          - git
          - lightdm
          - lightdm-gtk-greeter
          - neovim
          - network-manager-applet
          - nodejs
          - numlockx
          - picom
          - pulseaudio
          - pulseaudio-alsa
          - python
          - python-pip
          - sxhkd
          - tmux
          - xf86-video-vmware
          - xorg-server
          - xorg-xrdb
          - xorg-xsetroot
        state: present

    - name: Install AUR Packages
      aur:
        name:
          - polybar
          - xinit-xsession
        state: present

    - name: Enable Window Manager Service
      become: true
      service:
        name: lightdm.service
        enabled: yes

    - name: Create User
      become: true
      user:
        name: jtdubs
        comment: Justin Dubs
        group: wheel
        shell: /usr/bin/fish
        state: present
        password: "{{ '' | password_hash('sha512') }}"
        update_password: on_create

    - name: Clone Dotfiles
      become: true
      become_user: jtdubs
      git:
        repo: "https://github.com/jtdubs/dotfiles.git"
        dest: /home/jtdubs/dotfiles

    - name: Install Dotfile Requirements
      become: true
      become_user: jtdubs
      pip:
        requirements: /home/jtdubs/dotfiles/requirements.txt

    - name: Install Dotfiles
      become: true
      become_user: jtdubs
      shell:
        chdir: /home/jtdubs/dotfiles
        cmd: ./sync.py
        creates: /home/jtdubs/.xsession
