- name: Provision Image
  hosts: default

  tasks:
    - name: Install Packages
      become: true
      package:
        name:
          - alacritty
          - bspwm
          - dmenu
          - exa
          - feh
          - firefox
          - fish
          - fzf
          - git
          - lightdm
          - lightdm-gtk-greeter
          - neovim
          - network-manager-applet
          - nodejs
          - numlockx
          - picom
          - pulseaudio
          - pulseaudio-alsa
          - python
          - python-pip
          - sxhkd
          - tmux
          - xf86-video-vmware
          - xorg-server
          - xorg-xrdb
          - xorg-xsetroot
        state: present

    - name: Install AUR Packages
      aur:
        name:
          - polybar
          - xinit-xsession
        state: present

    - name: Enable Window Manager Service
      become: true
      service:
        name: lightdm.service
        enabled: yes

    - name: Create User
      become: true
      user:
        name: jtdubs
        comment: Justin Dubs
        group: wheel
        shell: /usr/bin/fish
        state: present

# https://github.com/jtdubs/dotfiles.git
