# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "dc" do |box|
    box.vm.box = "ws19-base"
    box.vm.hostname = "dc"
    box.vm.network "private_network", ip: "192.168.64.8"
    box.vm.synced_folder ".", "/vagrant", disabled: true
    box.vm.communicator = "winrm"
    box.winrm.password = "vagrant"
    box.winrm.username = "vagrant"
    box.winrm.transport = :plaintext
    box.winrm.basic_auth_only = true

    box.vm.provider "virtualbox" do |provider|
      provider.linked_clone = true
      provider.cpus = "2"
      provider.memory = "4096"
    end

    # sysprep to give us a unique machine RID
    box.vm.provision "windows-sysprep"

    # setup active directory
    box.vm.provision "shell", path: "files/Create-AD-Forest.ps1", reboot: true
    box.vm.provision "shell", path: "files/Configure-DC.ps1"
    box.vm.provision "shell", path: "files/Create-Domain-Users.ps1"
  end

  config.vm.define "web" do |box|
    box.vm.box = "ws19-base"
    box.vm.hostname = "web"
    box.vm.network "private_network", ip: "192.168.64.16"
    box.vm.synced_folder ".", "/vagrant", disabled: true
    box.vm.communicator = "winrm"
    box.winrm.password = "vagrant"
    box.winrm.username = "vagrant"

    box.vm.provider "virtualbox" do |provider|
      provider.linked_clone = true
      provider.cpus = "2"
      provider.memory = "4096"
    end

    # sysprep to give us a unique machine RID
    box.vm.provision "windows-sysprep"

    # join domain
    box.vm.provision "shell", path: "files/Join-Domain.ps1", reboot: true

  end

  config.vm.define "gamer" do |box|
    box.vm.box = "win10-updated"
    box.vm.hostname = "gamer"
    box.vm.network "private_network", ip: "192.168.64.32"
    box.vm.synced_folder ".", "/vagrant", disabled: true
    box.vm.communicator = "winrm"
    box.winrm.password = "vagrant"
    box.winrm.username = "vagrant"

    box.vm.provider "virtualbox" do |provider|
      provider.linked_clone = true
      provider.cpus = "2"
      provider.memory = "4096"
    end

    # sysprep to give us a unique machine RID
    box.vm.provision "windows-sysprep"

    # join domain
    box.vm.provision "shell", path: "files/Join-Domain.ps1", reboot: true
  end

  config.vm.define "hacker" do |box|
    box.vm.box = "ubuntu-xorg"
    box.vm.hostname = "hacker"
    box.vm.network "private_network", ip: "192.168.64.33"
    box.vm.synced_folder ".", "/vagrant", disabled: true
    box.vm.communicator = "ssh"
    box.ssh.username = "vagrant"
    box.ssh.private_key_path = "../../vagrant.id_rsa"

    box.vm.provider "virtualbox" do |provider|
      provider.linked_clone = true
      provider.cpus = "2"
      provider.memory = "4096"
    end

    # join domain
    box.vm.provision "shell", path: "files/join_domain.sh"
  end
end
