# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu-xorg"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.network "private_network", type: "dhcp"
    ubuntu.vm.synced_folder ".", "/vagrant", disabled: true
    ubuntu.vm.communicator = "ssh"
    ubuntu.ssh.private_key_path = "../../vagrant.id_rsa"
    ubuntu.ssh.username = "vagrant"
    # ubuntu.ssh.password = "vagrant"

    ubuntu.vm.provider "hyperv" do |vm|
      vm.linked_clone = true
      vm.enable_enhanced_session_mode = true
      vm.vm_integration_services = {
        # guest_service_interface: true,
        heartbeat: true,
        key_value_pair_exchange: true,
        shutdown: true,
        time_synchronization: true,
        vss: true,
      }
      vm.cpus = "4"
      vm.memory = "4096"
    end

    ubuntu.vm.provision "shell", path: "scripts/setup-ubuntu.sh", privileged: false
    ubuntu.vm.provision "shell", path: "scripts/setup-common.sh", privileged: false
  end

  config.vm.define "kali" do |kali|
    kali.vm.box = "kali-updated"
    kali.vm.hostname = "kali"
    kali.vm.network "private_network", type: "dhcp"
    kali.vm.synced_folder ".", "/vagrant", disabled: true
    kali.vm.communicator = "ssh"
    kali.ssh.private_key_path = "../../vagrant.id_rsa"
    kali.ssh.username = "vagrant"
    # kali.ssh.password = "vagrant"

    kali.vm.provider "hyperv" do |vm|
      vm.linked_clone = true
      vm.enable_enhanced_session_mode = true
      vm.vm_integration_services = {
        # guest_service_interface: true,
        heartbeat: true,
        key_value_pair_exchange: true,
        shutdown: true,
        time_synchronization: true,
        vss: true,
      }
      vm.cpus = "4"
      vm.memory = "4096"
    end

    kali.vm.provision "shell", path: "scripts/setup-kali.sh", privileged: false
    kali.vm.provision "shell", path: "scripts/setup-common.sh", privileged: false
  end

  config.vm.define "arch" do |arch|
    arch.vm.box = "arch-xorg"
    arch.vm.hostname = "arch"
    arch.vm.network "private_network", type: "dhcp"
    arch.vm.synced_folder ".", "/vagrant", disabled: true
    arch.vm.communicator = "ssh"
    arch.ssh.private_key_path = "../../vagrant.id_rsa"
    arch.ssh.username = "vagrant"
    # arch.ssh.password = "vagrant"

    arch.vm.provider "hyperv" do |vm|
      vm.linked_clone = true
      vm.enable_enhanced_session_mode = true
      vm.vm_integration_services = {
        # guest_service_interface: true,
        heartbeat: true,
        key_value_pair_exchange: true,
        shutdown: true,
        time_synchronization: true,
        vss: true,
      }
      vm.cpus = "4"
      vm.memory = "4096"
    end

    arch.vm.provision "shell", path: "scripts/setup-arch.sh", privileged: false
    arch.vm.provision "shell", path: "scripts/setup-common.sh", privileged: false
  end

  config.vm.define "win10" do |win10|
    win10.vm.box = "win10-workstation"
    win10.vm.hostname = "win10"
    win10.vm.network "private_network", type: "dhcp"
    win10.vm.synced_folder ".", "/vagrant", disabled: true
    win10.vm.communicator = "winrm"
    win10.winrm.password = "vagrant"
    win10.winrm.username = "vagrant"

    win10.vm.provider "hyperv" do |vm|
      vm.linked_clone = true
      vm.enable_enhanced_session_mode = true
      vm.vm_integration_services = {
        # guest_service_interface: true,
        heartbeat: true,
        key_value_pair_exchange: true,
        shutdown: true,
        time_synchronization: true,
        vss: true,
      }
      vm.cpus = "4"
      vm.memory = "4096"
    end
  end
end