# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu-workstation" do |ubuntu|
    ubuntu.vm.box = "ubuntu-workstation"
    ubuntu.vm.hostname = "ubuntu-workstation"
    ubuntu.vm.network "public_network"
    ubuntu.vm.communicator = "ssh"
    # ubuntu.ssh.private_key_path = "../../vagrant.id_rsa"
    ubuntu.ssh.username = "vagrant"
    ubuntu.ssh.password = "vagrant"

    ubuntu.vm.provider "hyperv" do |vm|
      vm.linked_clone = true
      vm.enable_enhanced_session_mode = true
      vm.vm_integration_services = {
        # guest_service_interface: true,
        heartbeat: true,
        key_value_pair_exchange: true,
        shutdown: true,
        time_synchronization: true,
        vss: true,
      }
      vm.cpus = "4"
      vm.memory = "4096"
    end
  end
end